---
title: "MutBiasFig4B"
author: "Scott Leighow"
date: "February 7, 2019"
output: html_document
---

## Figure 4B

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/Scott/Box Sync/MutBias/Figures/Figure4/Figure4B")
library(ggplot2)
library(reshape)
rm(list=ls())
```

## Plot Simulation

```{r}

df = read.csv("OutgrowthFigure.csv",header=F)
colnames(df) = c("time","WT","E255K")
df[df==0] = NA

ggplot(df,aes(x=time/365))+theme_bw()+
  geom_step(aes(y=log10(WT),color=factor("WT",levels=c("WT","E255K"))),size=1.5)+
  geom_step(aes(y=log10(E255K),color=factor("E255K",levels=c("WT","E255K"))),size=1.5)+
  xlab("Time [years]")+ylab("Population Size [cells]")+
  ggtitle("Stochastic Leukemic Blood Cell Dynamics")+
  scale_y_continuous(breaks=c(6,8,10,12),labels=parse(text=c("10^6","10^8","10^10","10^12")))+
  scale_x_continuous(breaks=c(0,3,6,9))+
  scale_color_manual(values=c("#ee1d23","#2abafc"),name="Genotype")+
  theme(
    plot.title=element_text(size=20,face="bold",hjust=0.5),
    axis.title=element_text(size=18,face="bold"),
    axis.text=element_text(size=18,color="black"),
    legend.position=c(0.1,0.9),
    legend.background=element_rect(fill="gray90"),
    legend.text=element_text(size=16),
    legend.title=element_text(size=16,face="bold")
  )

# ggsave("OutgrowthFigure.pdf",width=8,height=7)

# ggplot(df,aes(x=time/365))+theme_bw()+
#   geom_step(aes(y=log10(WT),color=factor("WT",levels=c("WT","E255K"))),size=1)+
#   geom_step(aes(y=log10(E255K),color=factor("E255K",levels=c("WT","E255K"))),size=1)+
#   xlab("Time")+ylab("Pop Size")+
#   # ggtitle("Stochastic Leukemic Blood Cell Dynamics")+
#   scale_y_continuous(breaks=c())+#,labels=parse(text=c("10^6","10^8","10^10","10^12")))+
#   scale_x_continuous(breaks=c())+
#   scale_color_manual(values=c("#ee1d23","#2abafc"),name="Genotype")+
#   theme(
#     plot.title=element_text(size=20,face="bold",hjust=0.5),
#     axis.title=element_text(size=18,face="bold"),
#     axis.text=element_text(size=18,color="black"),
#     legend.position=c(0.1,0.9),
#     legend.background=element_rect(fill="gray90"),
#     legend.text=element_text(size=16),
#     legend.title=element_text(size=16,face="bold")
#   )
# 
# ggsave("OutgrowthFigureThin.pdf",width=8,height=7)

```

